import { test, expect } from '@playwright/test'

const password = 'dayora browser password 123'
async function login(page, email, secret = password) {
  await page.goto('/#login')
  await page.getByLabel('Email address', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(secret)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('main h1')).toHaveText('Dashboard')
}
async function logout(page) {
  await page.goto('/#settings'); await page.getByRole('button', { name: 'Security', exact: true }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back', exact: true })).toBeVisible()
}
async function workspace(page) { const response = await page.request.get('/api/workspace'); expect(response.ok()).toBeTruthy(); return response.json() }
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }) })

test('signup, verification, password reset and protected routes with real backend', async ({ page }) => {
  await page.goto('/#tasks')
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  await page.getByRole('link', { name: 'Create an account' }).click()
  await page.getByLabel('Full name').fill('New Account')
  await page.getByLabel('Email address').fill('new-account@example.com')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('verification')
  await page.getByRole('link', { name: 'Back to sign in' }).click()
  await page.getByLabel('Email address').fill('new-account@example.com')
  const resent = page.waitForResponse((response) => response.url().endsWith('/auth/resend-verification') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Resend verification email' }).click()
  expect((await resent).status()).toBe(202)
  await expect(page.getByRole('status')).toContainText('verification')
  const mail = await (await page.request.get('/api/__test/mail')).json()
  const verification = mail.findLast((item) => item.email === 'new-account@example.com' && item.purpose === 'verify')
  const verificationUrl = verification.text.match(/Verify email: (\S+)/)[1]
  await page.goto(verificationUrl)
  await page.getByRole('button', { name: 'Verify email', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Email verified')
  const replay = await page.request.post('/api/auth/verify-email', { headers: { Origin: 'http://127.0.0.1:4173' }, data: { token: verification.token } })
  expect(replay.status()).toBe(400)
  await page.getByLabel('Email address', { exact: true }).fill('new-account@example.com')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('main h1')).toHaveText('Dashboard')
  expect((await workspace(page)).collections.tasks).toEqual([])
  await logout(page)
  await page.getByRole('link', { name: 'Forgot password?' }).click()
  await page.getByLabel('Email address').fill('new-account@example.com')
  await page.getByRole('button', { name: 'Send reset link' }).click()
  await expect(page.getByRole('status')).toContainText('reset link')
  const resetMail = await (await page.request.get('/api/__test/mail')).json()
  const reset = resetMail.findLast((item) => item.email === 'new-account@example.com' && item.purpose === 'reset')
  await page.goto(reset.text.match(/Reset password: (\S+)/)[1])
  await page.getByLabel('Password', { exact: true }).fill('new browser password 456')
  await page.getByRole('button', { name: 'Reset password', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Password reset')
  await login(page, 'new-account@example.com', 'new browser password 456')
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
})

test('account-specific project/task/team/calendar/timer/analytics persistence across devices and logout', async ({ page, browser }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message))
  await login(page, 'alice@example.com')
  await page.getByRole('button', { name: 'Add Project', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Project name').fill('Alice private project')
  await dialog.getByLabel('Deadline').fill('2026-10-20')
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.goto('/#team'); await page.getByRole('button', { name: 'Add member', exact: true }).click()
  await dialog.getByLabel('Full name', { exact: true }).fill('Alice Teammate')
  await dialog.getByLabel('Email address', { exact: true }).fill('teammate@example.com')
  await dialog.getByLabel('Role', { exact: true }).fill('Engineer')
  await dialog.getByRole('button', { name: 'Add member', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.goto('/#tasks'); await page.getByRole('button', { name: 'New Task', exact: true }).click()
  await dialog.getByLabel('Task name').fill('Alice private task')
  await dialog.getByLabel('Deadline', { exact: true }).fill('2026-10-20')
  await dialog.getByRole('combobox', { name: 'Project', exact: true }).selectOption({ label: 'Alice private project' })
  await dialog.getByRole('checkbox', { name: /Alice Teammate/ }).check()
  await dialog.getByRole('button', { name: 'Create task', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Alice private task', exact: true }).click()
  await dialog.getByLabel('New subtask').fill('Private checklist')
  await dialog.getByRole('button', { name: 'Add subtask' }).click()
  await dialog.getByLabel('Private checklist', { exact: true }).click()
  await expect(dialog.getByLabel('Private checklist', { exact: true })).toBeChecked()
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Complete Alice private task', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Completed', exact: true })).toContainText('Alice private task')
  await page.goto('/#calendar'); await page.getByRole('button', { name: 'New event', exact: true }).click()
  await dialog.getByLabel('Event name').fill('Alice private meeting')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-10-20')
  await dialog.getByLabel('Time', { exact: true }).fill('09:30')
  await dialog.getByRole('button', { name: 'Add event', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await expect(page.locator('.calendar-event').filter({ hasText: 'Alice private meeting' })).toBeVisible()
  await page.goto('/#dashboard'); await page.getByRole('button', { name: 'Start tracking', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pause', exact: true }).click(); await page.reload()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.getByRole('button', { name: 'Stop & save', exact: true }).click()
  await expect(page.locator('.timer-history summary')).toContainText('Saved sessions (1)')
  await page.goto('/#analytics'); await expect(page.locator('main h1')).toHaveText('Analytics')
  await expect(page.getByRole('progressbar', { name: 'Alice private project progress', exact: true })).toHaveAttribute('value', '100')
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export CSV', exact: true }).click(); expect((await downloadPromise).suggestedFilename()).toMatch(/^dayora-analytics/)
  const state = await workspace(page), taskId = state.collections.tasks[0].id
  const device = await browser.newContext({ baseURL: 'http://127.0.0.1:4173', reducedMotion: 'reduce' })
  const second = await device.newPage(); await login(second, 'alice@example.com'); await second.goto('/#tasks'); await expect(second.getByRole('button', { name: 'Alice private task', exact: true })).toBeVisible(); await device.close()
  await logout(page); await login(page, 'bob@example.com')
  expect((await workspace(page)).collections.tasks).toEqual([])
  expect((await page.request.get(`/api/workspace/tasks/${taskId}`)).status()).toBe(404)
  expect((await page.request.get('/api/admin/users')).status()).toBe(403)
  await logout(page); await login(page, 'alice@example.com')
  await page.goto('/#tasks'); await expect(page.getByRole('button', { name: 'Alice private task', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect(errors).toEqual([])
})

test('delayed session requests cannot restore an account after logout and account switching', async ({ page }) => {
  await login(page, 'alice@example.com')
  let release, received, finished
  const held = new Promise((resolve) => { release = resolve })
  const captured = new Promise((resolve) => { received = resolve })
  const delivered = new Promise((resolve) => { finished = resolve })
  let intercepted = false
  await page.route('**/api/auth/session', async (route) => {
    if (intercepted) { await route.continue(); return }
    intercepted = true
    const response = await route.fetch()
    received()
    await held
    await route.fulfill({ response }).catch(() => {}).finally(finished) // Logout aborts this old account's pending poll.
  })
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await captured
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Security', exact: true }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('Email address', { exact: true }).fill('switcher@example.com')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('main h1')).toHaveText('Dashboard')
  release()
  await delivered
  await expect(page.locator('.topbar-account')).toContainText('Switcher')
  await page.getByRole('link', { name: /^Tasks/ }).click()
  await expect(page.locator('main h1')).toHaveText('Tasks')
  await expect(page.locator('.topbar-account')).toContainText('Switcher')
  expect((await workspace(page)).collections.tasks).toEqual([])
  await expect(page.locator('.task-card')).toHaveCount(0)
})

test('anonymous data imports only after review and retains local backups', async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('fernly-projects', JSON.stringify([{ id: 'old-local-project', name: 'Local backup project', status: 'Pending', deadline: '2026-10-20' }])) })
  await login(page, 'migrator@example.com')
  expect((await workspace(page)).collections.projects).toEqual([])
  await page.getByRole('button', { name: 'Review local import', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Import into my empty workspace', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const imported = await workspace(page)
  expect(imported.collections.projects[0].name).toBe('Local backup project')
  expect(imported.collections.projects[0].id).not.toBe('old-local-project')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fernly-projects'))[0].id)).toBe('old-local-project')
})

test('shared browser tabs clear cached private data when another tab changes accounts', async ({ page }) => {
  await login(page, 'alice@example.com')
  const second = await page.context().newPage()
  await second.goto('/#settings')
  await second.getByRole('button', { name: 'Security', exact: true }).click()
  await second.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back', exact: true })).toBeVisible()
  await second.getByLabel('Email address', { exact: true }).fill('sharedtab@example.com')
  await second.getByLabel('Password', { exact: true }).fill(password)
  await second.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.topbar-account')).toContainText('Sharedtab')
  await page.getByRole('link', { name: /^Tasks/ }).click()
  await expect(page.locator('main h1')).toHaveText('Tasks')
  expect((await workspace(page)).collections.tasks).toEqual([])
  await expect(page.locator('.task-card')).toHaveCount(0)
  await second.close()
})

test('admin dashboard changes account access and preserves private-workspace isolation', async ({ page }) => {
  await login(page, 'administrator@example.com')
  await page.getByRole('button', { name: 'Dayora Admin', exact: true }).click()
  await expect(page.locator('main h1')).toHaveText('Dayora Admin')
  await page.getByLabel('Search accounts').fill('Bob')
  await expect(page.locator('.admin-table tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Manage account', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Account status').selectOption('false')
  await dialog.getByLabel('Reason').fill('Browser test deactivation')
  await dialog.getByLabel('Your administrator password').fill(password)
  await dialog.getByRole('button', { name: 'Save account changes', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await expect(page.locator('.admin-table')).toContainText('Inactive')
  await expect(page.getByText('Administrative audit log')).toBeVisible()
  expect((await workspace(page)).collections.tasks).toEqual([])
})

test('production authentication and account layouts are responsive with reduced motion', async ({ page }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#login')
  for (const width of [1440, 768, 390, 320]) { await page.setViewportSize({ width, height: 900 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
  await expect.poll(() => page.locator('.auth-card').evaluate((element) => Number(getComputedStyle(element).opacity))).toBe(1)
  await page.screenshot({ path: 'artifacts/phase5-login-mobile.png', fullPage: true })
  await login(page, 'alice@example.com')
  for (const route of ['tasks', 'calendar', 'team', 'analytics', 'settings']) {
    await page.goto(`/#${route}`); await expect(page.locator('main h1')).toBeVisible()
    for (const width of [1440, 390, 320]) { await page.setViewportSize({ width, height: 900 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
  }
  await page.getByLabel('Full name').fill('Updated account name')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Profile saved')
  await page.reload(); await expect(page.getByLabel('Full name')).toHaveValue('Updated account name')
  await page.getByRole('button', { name: 'Notifications', exact: true }).click()
  const preference = page.getByRole('switch').first()
  const initial = await preference.getAttribute('aria-checked')
  await preference.click()
  await expect.poll(async () => (await workspace(page)).collections.settings[0]?.value?.email).toBe(initial !== 'true')
  await page.reload(); await page.getByRole('button', { name: 'Notifications', exact: true }).click()
  await expect(page.getByRole('switch').first()).toHaveAttribute('aria-checked', String(initial !== 'true'))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#dashboard'); await expect(page.locator('main h1')).toHaveText('Dashboard')
  await expect.poll(() => page.locator('.time-tracker').evaluate((element) => Number(getComputedStyle(element).opacity))).toBe(1)
  await expect.poll(() => page.locator('.route-content').evaluate((element) => Number(getComputedStyle(element).opacity))).toBe(1)
  await page.screenshot({ path: 'artifacts/phase5-account-dashboard.png', fullPage: true })
  expect(errors).toEqual([])
})

test('Firebase browser login keeps tokens in memory and private profile images survive reload', async ({ page }) => {
  await page.goto('/#login')
  await page.getByLabel('Email address', { exact: true }).fill('alice@example.com')
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Keep me signed in').check()
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('main h1')).toHaveText('Dashboard')
  const cookies = await page.context().cookies()
  const session = cookies.find((cookie) => cookie.name === 'dayora-session')
  expect(session.httpOnly).toBe(true); expect(session.expires).toBeGreaterThan(Date.now() / 1000 + 13 * 86400)
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect(await page.evaluate(() => Object.keys(sessionStorage))).toEqual([])
  await page.goto('/#settings')
  await page.locator('input[type=file]').setInputFiles({ name: 'profile.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jOZkAAAAASUVORK5CYII=', 'base64') })
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Profile saved')
  await page.reload()
  const profile = (await (await page.request.get('/api/auth/session')).json()).user
  expect(profile.photo).toMatch(/^media:/)
  const loaded = page.waitForResponse((response) => response.url().endsWith(`/api/media/${profile.photo.slice(6)}`) && response.status() === 200)
  await page.reload(); await loaded
  await expect(page.locator('.profile-photo .avatar')).toHaveCSS('background-image', new RegExp(`/api/media/${profile.photo.slice(6)}`))
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
})
