import { test, expect } from '@playwright/test'
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('/#tasks'); await expect(page.locator('main h1')).toHaveText('Tasks') })
test('task CRUD, subtasks, filters, completion and persistence', async ({ page }) => {
  await page.getByRole('button', { name: 'New Task', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Task name').fill('Phase 3 task')
  await dialog.getByLabel('Description', { exact: true }).fill('Searchable delivery context')
  await dialog.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('Urgent')
  await dialog.getByLabel('Deadline', { exact: true }).fill('2026-10-06')
  await dialog.getByRole('combobox', { name: 'Project', exact: true }).selectOption({ label: 'Payments API v2' })
  await dialog.getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Phase 3 task', exact: true }).click()
  await dialog.getByLabel('New subtask').fill('Review delivery')
  await dialog.getByRole('button', { name: 'Add subtask' }).click()
  await dialog.getByLabel('Review delivery', { exact: true }).check()
  await expect(dialog.getByRole('progressbar')).toHaveAttribute('value', '100')
  await dialog.getByLabel('Task name').fill('Phase 3 edited')
  await dialog.getByRole('button', { name: 'Save changes' }).click()
  await page.reload()
  await page.getByLabel('Search tasks', { exact: true }).fill('delivery context')
  await expect(page.locator('.task-card')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('Low')
  await expect(page.locator('.task-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await page.getByRole('button', { name: 'Complete Phase 3 edited', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Completed', exact: true }).getByRole('button', { name: 'Phase 3 edited', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Completed', exact: true }).getByRole('button', { name: 'Phase 3 edited', exact: true }).click()
  await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
  await dialog.getByRole('button', { name: 'Delete task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Phase 3 edited', exact: true })).toHaveCount(0)
})
test('pointer drag between columns persists and keyboard sorting works', async ({ page }) => {
  const card = page.getByRole('region', { name: 'To Do', exact: true }).locator('.task-card').first()
  const title = await card.locator('.task-title-button').innerText()
  const handle = card.locator('.task-drag')
  const start = await handle.boundingBox()
  const target = await page.getByRole('region', { name: 'In Progress', exact: true }).boundingBox()
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down(); await page.mouse.move(start.x + 10, start.y + 10)
  await page.mouse.move(target.x + target.width / 2, target.y + 80, { steps: 15 }); await page.mouse.up()
  await expect(page.getByRole('region', { name: 'In Progress', exact: true }).getByRole('button', { name: title, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('region', { name: 'In Progress', exact: true }).getByRole('button', { name: title, exact: true })).toBeVisible()
  const column = page.getByRole('region', { name: 'To Do', exact: true })
  const first = await column.locator('.task-title-button').first().innerText()
  await column.locator('.task-drag').first().focus(); await page.keyboard.press('Space'); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Space')
  await expect(column.locator('.task-title-button').nth(1)).toHaveText(first)
})
test('mobile board has no overflow and task dialog traps focus', async ({ page }) => {
  for (const width of [1440, 768, 390, 320]) { await page.setViewportSize({ width, height: 900 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
  await page.getByRole('button', { name: 'New Task', exact: true }).click()
  for (let index = 0; index < 12; index++) { await page.keyboard.press('Tab'); expect(await page.evaluate(() => document.querySelector('[role="dialog"]').contains(document.activeElement))).toBe(true) }
  await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'New Task', exact: true })).toBeFocused()
})

