import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'
import { localScope, storageKey } from '../../src/repositories/createRepository.js'
const keys = Object.fromEntries(['tasks', 'projects', 'events', 'team', 'time-entries'].map((collection) => [collection, storageKey(localScope, collection)]))
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }); await page.clock.setFixedTime(new Date('2026-10-06T06:00:00Z')) })
const data = (page, collection) => page.evaluate((key) => JSON.parse(localStorage.getItem(key)).data, keys[collection])

test('calendar event CRUD, timezone conversion, search, views and persistence', async ({ page }) => {
  await page.goto('/#calendar'); await expect(page.locator('main h1')).toHaveText('Calendar')
  const initial = (await data(page, 'events')).length
  await page.getByRole('button', { name: 'New event', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Event name').fill('Phase 4 timezone meeting')
  await dialog.getByLabel('Date', { exact: true }).fill('2026-10-07')
  await dialog.getByLabel('Time', { exact: true }).fill('23:00')
  await dialog.getByLabel('Timezone', { exact: true }).fill('America/Los_Angeles')
  await dialog.getByRole('button', { name: 'Add event', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const day = page.locator('[data-date="2026-10-08"]')
  await expect(day.getByRole('button', { name: 'Meeting: Phase 4 timezone meeting', exact: true })).toContainText('11:30')
  await page.getByLabel('Search calendar').fill('timezone meeting')
  await expect(page.locator('.calendar-event')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Display timezone', exact: true }).selectOption('America/Los_Angeles')
  await expect(page.locator('[data-date="2026-10-07"]').getByRole('button', { name: 'Meeting: Phase 4 timezone meeting', exact: true })).toContainText('23:00')
  await page.getByRole('button', { name: 'New event', exact: true }).click(); await expect(dialog.getByLabel('Timezone', { exact: true })).toHaveValue('America/Los_Angeles'); await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await page.locator('.calendar-event').click()
  await dialog.getByLabel('Event name').fill('Phase 4 updated meeting')
  await dialog.getByLabel('Description').fill('Planning agenda')
  await dialog.getByRole('button', { name: 'Save changes' }).click()
  await page.reload(); await page.getByLabel('Search calendar').fill('Phase 4 updated')
  await expect(page.locator('.calendar-event')).toContainText('Phase 4 updated meeting')
  expect((await data(page, 'events')).length).toBe(initial + 1)
  const event = (await data(page, 'events')).find((item) => item.title === 'Phase 4 updated meeting')
  expect(event).toMatchObject({ ownerId: localScope.ownerId, workspaceId: localScope.workspaceId, timeZone: 'America/Los_Angeles', startsAt: Date.parse('2026-10-08T06:00Z') })
  await page.getByRole('button', { name: 'Week', exact: true }).click(); await expect(page.locator('.calendar-day')).toHaveCount(7)
  await page.getByRole('button', { name: 'Next week', exact: true }).click()
  await page.getByRole('button', { name: 'Day', exact: true }).click(); await expect(page.locator('.calendar-day')).toHaveCount(1)
  await page.getByRole('button', { name: 'Today', exact: true }).click(); await expect(page.locator('.calendar-day')).toHaveAttribute('data-date', '2026-10-06')
  await page.getByRole('button', { name: 'Month', exact: true }).click()
  await page.locator('.calendar-event').click(); await dialog.getByRole('button', { name: 'Delete', exact: true }).click(); await dialog.getByRole('button', { name: 'Delete event', exact: true }).click()
  await expect(dialog).not.toBeVisible(); expect((await data(page, 'events')).length).toBe(initial)
})
test('task and project deadlines synchronize without extra persisted events', async ({ page }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Add Project', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Project name').fill('Calendar-linked project'); await dialog.getByLabel('Deadline').fill('2026-10-07')
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click(); await expect(dialog).not.toBeVisible()
  const initial = (await data(page, 'events')).length
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  await dialog.getByLabel('Task name').fill('Calendar-linked task'); await dialog.getByLabel('Deadline').fill('2026-10-07')
  await dialog.getByRole('combobox', { name: 'Project', exact: true }).selectOption({ label: 'Calendar-linked project' })
  await dialog.getByRole('button', { name: 'Create task', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await page.goto('/#calendar'); await page.getByLabel('Search calendar').fill('Calendar-linked')
  const day = page.locator('[data-date="2026-10-07"]')
  await expect(day.locator('.calendar-event')).toHaveCount(2)
  await day.getByRole('button', { name: 'Task deadline: Calendar-linked task', exact: true }).click()
  await expect(dialog).toContainText('Task details'); await dialog.getByLabel('Deadline').fill('2026-10-09'); await dialog.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.locator('[data-date="2026-10-09"] .calendar-entry--task')).toContainText('Calendar-linked task')
  await day.getByRole('button', { name: 'Project deadline: Calendar-linked project', exact: true }).click()
  await dialog.getByRole('button', { name: 'Edit project' }).click(); await dialog.getByLabel('Deadline').fill('2026-10-10'); await dialog.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.locator('[data-date="2026-10-10"] .calendar-entry--project')).toContainText('Calendar-linked project')
  expect((await data(page, 'events')).length).toBe(initial)
  await page.reload(); await page.getByRole('combobox', { name: 'Entry type', exact: true }).selectOption('task')
  await page.getByLabel('Search calendar').fill('Calendar-linked'); await expect(page.locator('.calendar-event')).toHaveCount(1)
})
test('team member CRUD, pictures, assignments, completion and removal persist', async ({ page }) => {
  await page.goto('/#team'); await page.getByRole('button', { name: 'Add member', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Full name').fill('Avery Patel'); await dialog.getByLabel('Email address').fill('avery@example.com'); await dialog.getByLabel('Role', { exact: true }).fill('Research designer')
  await dialog.getByRole('combobox', { name: 'Department', exact: true }).selectOption('Design')
  await dialog.getByLabel('Profile picture').setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7GQAAAAASUVORK5CYII=', 'base64') })
  await dialog.getByRole('button', { name: 'Add member', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await page.getByLabel('Search team').fill('avery'); await expect(page.locator('.member-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'View Avery Patel', exact: true }).click()
  await dialog.getByRole('combobox', { name: 'Task to assign', exact: true }).selectOption({ label: 'Saved filters for projects' })
  await dialog.getByRole('button', { name: 'Assign task', exact: true }).click(); await expect(dialog.getByRole('heading', { name: '1 assigned · 0 completed' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Saved filters for projects', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Task details', exact: true })).toBeVisible()
  await expect(dialog.getByLabel('Avery Patel', { exact: true })).toBeChecked()
  await dialog.getByRole('button', { name: 'Complete task', exact: true }).click(); await expect(dialog).not.toBeVisible()
  await expect(page.locator('.member-card')).toContainText('1 completed')
  await page.getByRole('button', { name: 'View Avery Patel', exact: true }).click(); await dialog.getByLabel('Full name').fill('Avery Shah'); await dialog.getByRole('button', { name: 'Save changes' }).click()
  await page.reload(); await page.getByLabel('Search team').fill('avery'); await page.getByRole('combobox', { name: 'Department', exact: true }).selectOption('Design')
  await expect(page.locator('.member-card')).toContainText('Avery Shah')
  const member = (await data(page, 'team')).find((item) => item.name === 'Avery Shah')
  expect(member.photo).toMatch(/^data:image\/png;base64,/)
  expect((await data(page, 'tasks')).find((item) => item.title === 'Saved filters for projects').assigneeIds).toContain(member.id)
  await page.getByRole('button', { name: 'View Avery Shah', exact: true }).click(); await dialog.getByRole('button', { name: 'Remove', exact: true }).click(); await dialog.getByRole('button', { name: 'Remove member', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View Avery Shah', exact: true })).toHaveCount(0)
  const task = (await data(page, 'tasks')).find((item) => item.title === 'Saved filters for projects')
  expect(task.assigneeIds).not.toContain(member.id); expect(task.status).toBe('Done'); expect(typeof task.completedAt).toBe('number')
})
test('analytics, project progress, saved time and CSV export use persisted records', async ({ page }) => {
  await page.addInitScript(() => {
    const now = Date.parse('2026-10-06T05:00Z')
    localStorage.setItem('fernly-projects', JSON.stringify([{ id: 'real-project', name: 'Actual project', deadline: '2026-10-10' }]))
    localStorage.setItem('fernly-tasks', JSON.stringify([{ id: 'real-done', title: 'Actual done task', status: 'Done', priority: 'High', projectId: 'real-project', completedAt: now, createdAt: now - 86400000, dueDate: '2026-10-06', assignees: ['NC'] }, { id: 'real-open', title: 'Actual overdue task', status: 'To do', priority: 'Urgent', projectId: 'real-project', dueDate: '2026-10-05', assignees: ['NC'] }]))
    localStorage.setItem('fernly-tracker-v1', JSON.stringify({ active: { id: 'active', startedAt: now, runningSince: now, segments: [], projectId: 'real-project' }, sessions: [{ id: 'saved', projectId: 'real-project', startedAt: now - 3600000, endedAt: now, duration: 3600000, segments: [{ start: now - 3600000, end: now }], runningSince: null }] }))
  })
  await page.goto('/#analytics'); await expect(page.locator('main h1')).toHaveText('Analytics')
  const metric = (label) => page.locator('.analytics-stat').filter({ has: page.locator('span').filter({ hasText: new RegExp(`^${label}$`) }) }).locator('p[aria-label]')
  await expect(metric('Tasks completed')).toHaveAttribute('aria-label', '1'); await expect(metric('Overdue tasks')).toHaveAttribute('aria-label', '1')
  await expect(page.getByTestId('analytics-tracked')).toHaveText('01:00:00')
  await expect(page.locator('.performance-table')).toContainText('1 / 2'); await expect(page.getByRole('progressbar', { name: 'Actual project progress', exact: true })).toHaveAttribute('value', '50')
  await page.getByRole('button', { name: 'Weekly', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Weekly task completion' })).toBeVisible()
  await page.getByText('Customize', { exact: true }).click(); await page.getByRole('checkbox', { name: 'Created tasks', exact: true }).uncheck()
  await expect(page.locator('.analytics-main-chart .recharts-bar')).toHaveCount(1)
  await page.getByRole('checkbox', { name: 'Created tasks', exact: true }).check(); await expect(page.locator('.analytics-main-chart .recharts-bar')).toHaveCount(2)
  await page.getByRole('combobox', { name: 'Analytics period', exact: true }).selectOption('7')
  await page.getByRole('combobox', { name: 'Analytics project', exact: true }).selectOption('real-project')
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export CSV', exact: true }).click(); const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('dayora-analytics-2026-10-06.csv')
  const contents = await fs.readFile(await download.path(), 'utf8')
  expect(contents).toContain('"Project","Actual project","","1","1","2","50","1.0000"')
  await page.goto('/'); await expect(page.getByRole('progressbar', { name: 'Actual project task progress', exact: true })).toHaveAttribute('value', '50')
  await expect(page.locator('.saved-time-note')).toContainText('01:00:00')
  await expect(page.locator('.dashboard-phase4')).toContainText('Actual project')
})
test('phase 4 responsive pages and reduced-motion modals have no browser errors', async ({ page }) => {
  const errors = []; page.on('pageerror', (error) => errors.push(error.message))
  for (const route of ['calendar', 'team', 'analytics']) {
    await page.goto(`/#${route}`); await expect(page.locator('main h1')).toBeVisible()
    for (const width of [1440, 1024, 768, 390, 320]) { await page.setViewportSize({ width, height: 900 }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true) }
  }
  await page.goto('/#calendar'); await page.getByRole('button', { name: 'New event', exact: true }).click()
  for (let index = 0; index < 16; index++) { await page.keyboard.press('Tab'); expect(await page.evaluate(() => document.querySelector('[role="dialog"]').contains(document.activeElement))).toBe(true) }
  await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'New event', exact: true })).toBeFocused()
  expect(await page.locator('.calendar-day').first().evaluate((element) => parseFloat(getComputedStyle(element).transitionDuration))).toBeLessThanOrEqual(.001)
  await page.emulateMedia({ reducedMotion: 'no-preference' }); await page.getByRole('button', { name: 'Week', exact: true }).click(); await expect(page.locator('.calendar-day')).toHaveCount(7)
  await page.getByRole('button', { name: 'Day', exact: true }).click(); await expect(page.locator('.calendar-day')).toHaveCount(1)
  expect(errors).toEqual([])
})
