
import { useMemo, useState } from 'react'
import { motion, useReducedMotion } from 'motion/react'
import { Download, Printer, SlidersHorizontal } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import Avatar from '../components/Avatar'
import SectionTitle from '../components/SectionTitle'
import AnimatedNumber from '../components/AnimatedNumber'
import { productivityAnalytics } from '../services/analytics'
import { analyticsCsv, downloadCsv } from '../services/export'
import { defaultTimeZone } from '../services/calendar'
import { formatDuration } from '../utils/timer'
import { cardEntrance, staggerCards } from '../styles/motion'
import useNow from '../hooks/useNow'

const colors = ['#98ae9d', '#dec9b1', '#a5b6c3', '#c09a9c']
function DataTable({ rows }) { return <details className="chart-data"><summary>View chart data</summary><div className="phase4-table-scroll"><table><thead><tr><th>Date</th><th>Created</th><th>Completed</th><th>Tracked hours</th></tr></thead><tbody>{rows.map((row) => <tr key={row.date}><td>{row.date}</td><td>{row.created}</td><td>{row.completed}</td><td>{row.trackedHours.toFixed(2)}</td></tr>)}</tbody></table></div></details> }
function TrendChart({ rows, reduced, area = false, showCompleted = true, showCreated = true }) {
  const Chart = area ? AreaChart : BarChart
  return <><div className="chart-large"><ResponsiveContainer width="100%" height="100%"><Chart data={rows} accessibilityLayer margin={{ top: 10, right: 10, left: -18, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#efefeb" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#929b8d', fontSize: 10 }} minTickGap={24} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} width={45} tick={{ fill: '#929b8d', fontSize: 10 }} /><Tooltip contentStyle={{ borderRadius: 12, border: '1px solid #e7ece2', fontSize: 12 }} />{area ? <>{showCompleted && <Area name="Completed" dataKey="completed" stroke="#829d88" fill="#dfe9df" isAnimationActive={!reduced} animationDuration={500} />}{showCreated && <Area name="Created" dataKey="created" stroke="#c4aa8b" fill="#f4ece2" isAnimationActive={!reduced} animationDuration={500} />}</> : <>{showCompleted && <Bar name="Completed" dataKey="completed" fill={colors[0]} radius={[4, 4, 0, 0]} isAnimationActive={!reduced} animationDuration={500} />}{showCreated && <Bar name="Created" dataKey="created" fill={colors[1]} radius={[4, 4, 0, 0]} isAnimationActive={!reduced} animationDuration={500} />}</>}</Chart></ResponsiveContainer></div><DataTable rows={rows} /></>
}
export default function AnalyticsPage({ tasks, projects, team, timeEntries, onProject, onTask, onMember }) {
  const now = useNow(), reduced = useReducedMotion()
  const [days, setDays] = useState(30), [projectId, setProjectId] = useState(''), [group, setGroup] = useState('Daily')
  const [showCompleted, setShowCompleted] = useState(true), [showCreated, setShowCreated] = useState(true)
  const report = useMemo(() => productivityAnalytics({ tasks, projects, team, timeEntries }, { days, projectId, now }), [tasks, projects, team, timeEntries, days, projectId, now])
  const stats = [{ label: 'Tasks completed', value: report.completedInPeriod, note: 'Completions recorded in this period' }, { label: 'Pending tasks', value: report.pending, note: 'Current workspace workload' }, { label: 'Overdue tasks', value: report.overdue, note: 'Open tasks past their deadline' }]
  return <section className="page-content" aria-label="Analytics"><SectionTitle title="Analytics" description="A thoughtful look at your team's progress, from saved workspace records." actions={<><button className="button button--outline" onClick={() => window.print()}><Printer size={16} /> Print report</button><button className="button button--outline" onClick={() => downloadCsv(analyticsCsv(report), `dayora-analytics-${report.today}.csv`)}><Download size={16} /> Export CSV</button></>} />
    <div className="phase4-filters"><label>Analytics period<select value={days} onChange={(e) => setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last 365 days</option></select></label><label>Analytics project<select value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">All projects</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><p className="phase4-period">{report.firstDate} – {report.today} · {defaultTimeZone}</p></div>
    <motion.div variants={staggerCards} initial="hidden" animate="visible"><div className="analytics-stats phase4-metrics">{stats.map((stat) => <motion.article variants={cardEntrance} className="panel analytics-stat" key={stat.label}><span>{stat.label}</span><AnimatedNumber value={stat.value} /><small>{stat.note}</small></motion.article>)}<motion.article variants={cardEntrance} className="panel analytics-stat"><span>Saved tracked time</span><strong data-testid="analytics-tracked">{formatDuration(report.trackedMilliseconds)}</strong><small>Saved sessions · Excludes active timers</small></motion.article></div>
      <p className="analytics-history-note">{report.unknownCompletionDates} completed tasks have no recorded completion date and are excluded from historical trends. On-time delivery: {report.onTimeRate === null ? 'No dated completions in this period' : `${report.onTimeRate}% of dated completions`}.</p>
      <div className="analytics-charts"><motion.article variants={cardEntrance} className="panel analytics-main-chart"><div className="panel-heading"><div><h2>{group} task completion</h2><p>Created and completed tasks over the selected period.</p></div><div className="view-switch" role="group" aria-label="Completion grouping">{['Daily', 'Weekly'].map((value) => <button aria-pressed={group === value} className={group === value ? 'is-selected' : ''} key={value} onClick={() => setGroup(value)}>{value}</button>)}</div></div><details className="analytics-customize"><summary className="button button--soft button--small"><SlidersHorizontal size={14} /> Customize</summary><div className="menu-popover analytics-options"><label><input type="checkbox" checked={showCompleted} onChange={(e) => setShowCompleted(e.target.checked)} />Completed tasks</label><label><input type="checkbox" checked={showCreated} onChange={(e) => setShowCreated(e.target.checked)} />Created tasks</label></div></details><div className="chart-legend"><span><i className="legend-dot legend-dot--sage" />Completed</span><span><i className="legend-dot legend-dot--tan" />Created</span></div><TrendChart rows={group === 'Daily' ? report.daily : report.weekly} reduced={reduced} showCompleted={showCompleted} showCreated={showCreated} /></motion.article>
        <motion.article variants={cardEntrance} className="panel breakdown-panel"><div className="panel-heading"><div><h2>Completed versus pending</h2><p>Current task state</p></div></div><div className="donut-wrap">{report.total ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={report.breakdown} dataKey="count" nameKey="name" innerRadius={65} outerRadius={83} stroke="none" paddingAngle={3} isAnimationActive={!reduced} animationDuration={500}>{report.breakdown.map((row, index) => <Cell fill={colors[index]} key={row.name} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer> : <p className="empty-search">No tasks in this view</p>}<div className="donut-center"><strong>{report.total}</strong><span>Total tasks</span></div></div><div className="breakdown-legend">{report.breakdown.map((row, index) => <div key={row.name}><span><i style={{ background: colors[index] }} />{row.name}</span><b>{row.count} tasks</b></div>)}</div></motion.article>
      </div>
      <div className="phase4-chart-grid"><motion.article variants={cardEntrance} className="panel phase4-panel"><div className="panel-heading"><div><h2>Monthly productivity trends</h2><p>Calendar months intersecting the selected period.</p></div></div><TrendChart rows={report.monthly} reduced={reduced} area showCompleted={showCompleted} showCreated={showCreated} /></motion.article><motion.article variants={cardEntrance} className="panel phase4-panel"><div className="panel-heading"><div><h2>Task priority distribution</h2><p>Actual tasks by priority</p></div></div><div className="chart-large"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.priorities} accessibilityLayer><CartesianGrid vertical={false} stroke="#efefeb" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} width={30} /><Tooltip /><Bar name="Tasks" dataKey="count" radius={[5, 5, 0, 0]} isAnimationActive={!reduced} animationDuration={500}>{report.priorities.map((row, index) => <Cell key={row.name} fill={colors[index]} />)}</Bar></BarChart></ResponsiveContainer></div><div className="priority-counts">{report.priorities.map((row) => <span key={row.name}>{row.name}: <b>{row.count}</b></span>)}</div></motion.article></div>
      <motion.article variants={cardEntrance} className="panel phase4-panel"><div className="panel-heading"><div><h2>Project performance</h2><p>Progress comes from associated tasks; time uses saved sessions in this period.</p></div></div><div className="phase4-table-scroll"><table className="performance-table"><thead><tr><th>Project</th><th>Completed / Total</th><th>Task progress</th><th>Saved time</th></tr></thead><tbody>{report.projects.map((project) => <tr key={project.id}><td><button className="text-link" onClick={() => onProject(project.id)}>{project.name}</button></td><td>{project.completed} / {project.total}</td><td><progress aria-label={`${project.name} progress`} value={project.progress} max="100" /> {project.progress}%</td><td>{formatDuration(project.trackedMilliseconds)}</td></tr>)}</tbody></table></div>{!report.projects.length && <p className="empty-search">No projects in this view.</p>}</motion.article>
      <motion.article variants={cardEntrance} className="panel team-progress"><div className="panel-heading"><div><h2>Team workload</h2><p>Current assignments and completion, including co-assigned tasks.</p></div></div>{report.workload.map((member) => <div className="progress-row" key={member.id}><Avatar initials={member.initials} color={member.color} photo={member.photo} /><button className="progress-row__name phase4-person-link" onClick={() => onMember(member.id)}><strong>{member.name}</strong><span>{member.completed}/{member.total} completed</span></button><div className="progress-track" role="progressbar" aria-label={`${member.name} task progress`} aria-valuenow={member.progress} aria-valuemin={0} aria-valuemax={100}><motion.i animate={{ width: `${member.progress}%` }} transition={{ duration: reduced ? 0 : .5 }} /></div><b>{member.pending} open</b></div>)}</motion.article>
      <motion.article variants={cardEntrance} className="panel phase4-panel"><div className="panel-heading"><div><h2>Overdue tasks</h2><p>Open work that needs a fresh plan.</p></div></div>{report.overdueTasks.length ? report.overdueTasks.map((task) => <button key={task.id} className="overdue-task" onClick={() => onTask(task.id)}><strong>{task.title}</strong><span>{task.dueDate} · {task.priority}</span></button>) : <p className="empty-search">No overdue tasks in this view.</p>}</motion.article>
    </motion.div>
  </section>
}
