import { useState } from 'react'
import useAuth from '../hooks/useAuth'
import { authService } from '../services/authService'
import { readMemberPhoto } from '../services/team'
import Avatar from '../components/Avatar'

export default function ProfilePage({ security = false }) {
  const { user, updateUser, signOut } = useAuth()
  const [photo, setPhoto] = useState(user.photo || ''), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const run = async (operation) => { setBusy(true); setError(''); setMessage(''); try { await operation() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <article className="panel settings-card"><div className="settings-card__heading"><h2>{security ? 'Account security' : 'Profile information'}</h2><p>{security ? 'Manage your password and server-side sessions.' : 'Your profile belongs to your Dayora account.'}</p></div>{error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status">{message}</p>}
    {security ? <><form className="settings-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); run(async () => { await authService.changePassword({ currentPassword: data.get('currentPassword'), password: data.get('password') }); updateUser(null); window.location.hash = 'login' }) }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128} /></label><label>New password<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={128} /></label><button className="button button--primary" disabled={busy}>Change password and sign out</button></form><div className="account-actions profile-security"><button className="button button--outline" disabled={busy} onClick={() => run(async () => setMessage((await authService.logoutOthers()).message))}>Sign out other devices</button><button className="button button--outline" disabled={busy} onClick={() => run(signOut)}>Sign out</button></div><p>Two-factor authentication is not currently available.</p></> : <><div className="profile-photo"><Avatar initials={user.name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2)} photo={photo} /><label className="button button--outline button--small profile-upload">Upload photo<input type="file" disabled={user.photoUploadsEnabled === false} accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event) => run(async () => setPhoto(await readMemberPhoto(event.target.files?.[0])))} /></label></div>{user.photoUploadsEnabled === false && <p>Photo uploads are unavailable. You can still update your profile details.</p>}<form className="settings-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); run(async () => { updateUser(await authService.profile({ name: data.get('name'), jobTitle: data.get('jobTitle'), about: data.get('about'), photo })); setMessage('Profile saved.') }) }}><label>Full name<input name="name" defaultValue={user.name} maxLength={100} required /></label><label>Verified email<input value={user.email} readOnly type="email" /><small>Email changes require a verification workflow and are not available yet.</small></label><label>Role<input name="jobTitle" defaultValue={user.jobTitle} maxLength={100} /></label><label>About<textarea name="about" defaultValue={user.about} maxLength={2000} rows={3} /></label><button className="button button--primary" disabled={busy}>Save changes</button></form></>}
  </article>
}
